deployment:
  tasks:
    - name: Install dependencies
      command: /opt/cpanel/ea-nodejs16/bin/npm install

    - name: Build Vue App
      command: /opt/cpanel/ea-nodejs16/bin/npm run build

    - name: Deploy to public_html
      command: rsync -av --delete dist/ /home/<cpanel_username>/public_html/